### ISSUE TITLE
German scorings with recyclarr

### ISSUE THREAD

**Issue by andybroger** [andybroger/radarr-sonarr-german-dual-language#1]
Create a guide for recyclarr

steps:

First add the custom formats from this repo

then configure recyclarr: 
radarr: https://recyclarr.dev/wiki/sqp-configs/
sonarr: https://recyclarr.dev/wiki/guide-configs/

## Add following to the quality profiles

```
    quality_profiles:
      - name: SQP-1 (2160p)
        min_format_score: 2000
        reset_unmatched_scores: false
```

## sync profiles

scores for german formats:

- German DL 2200
- German DL 2 2200
- Language: German Only 2000
- Language: Not ENG/GER -20000
- MIC DUB: -20000
